### ISSUE TITLE
Ask for python code (Empatica-E4-LSL)

### ISSUE THREAD

**Issue by ruby831224** [HectorCarral/Empatica-E4-LSL#1]
Hello, I have request you a question
I refer to your python code for Empatica E4 LSL
But for your code "s.send("device_connect " + deviceID + "\r\n")", it shows unknown command(below first figure)
And the E4 streaming server shows the connections "no connections" (below second figure)
Do you know how to solve this question?
Thanks!

Best,
Yu
![python code](https://user-images.githubusercontent.com/53419935/62024316-1fd3cc00-b207-11e9-9a1f-7c2a051d9da1.JPG)
![streaming server](https://user-images.githubusercontent.com/53419935/62024427-80630900-b207-11e9-8e62-a6eb43432b08.JPG)

**Comment by HectorCarral** [comment]
Hi Yu,

Sorry for the delay in my response. The code was working for us on several machines without that issue. I don't know what could be the cause. In any case, I just uploaded a new version that changes the code, including the line to send the device_connect command. I hope the problem is solved for you.
